
# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

# Keybase
include:
  - .well-known

# White-listed plugins
gems:
  - jekyll-sitemap

title: Alessandro Bessi
email: alessandro dot bessi at mail dot com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Alessandro. I do research and development at Nextbit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bessimaestro
github_username:  alessandrobessi
linkedin_username: alessandrobessi

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
